language: c

matrix:
  include:
    - dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-7
            - cmake-data
            - cmake
        env:
          - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - cmake --build .